export const CREATE_MARKET = "CREATE_MARKET";
export const RESET_MARKET = "RESET_MARKET";
export const SET_MARRIAGE_MARKET_IS_LOADING = "SET_MARRIAGE_MARKET_IS_LOADING";
export const CREATE_PROPOSALS = "CREATE_PROPOSALS";
export const ACCEPT_PROPOSALS = "ACCEPT_PROPOSALS";
export const SET_AVATAR_CLASS = "SET_AVATAR_CLASS";
export const CLEAR_AVATAR_CLASS = "CLEAR_AVATAR_CLASS";
